language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_TOKEN
    - secure: HIVg/g0eokKX7JbK5UxV+lN1D8XRB9p1uL5HY7a2CP+Kuycr79/9aXqxBxpNhv6SpKr/5O7pIMbc7w0negLDEU/yEEJINY1yUm5YxDLkeMgWKxLKbJH5h8ve1iu5moX+MoYcmdSxvTBYpkVsGHz3ZMf+q0UC4Qo2QM6A7CuWL1jIqb7aAk7RbE8WWZOjvEzt3DRrQ6Df0a6pThqkfNlMovfsfLMvXncwEVfiVTsSo4GT/g4auG2396N5JL8pmyBdHnQF6pC+CbCjItA59JUQsZcwkGBbyhEaCNvq1Fj51Vi1inq7Ildv7WBJX6hgBedy2OLkDdBLW1ih1PyPBKVJLodDs9REnFq62DbG0obchK5uYlQ3r6UbFwJWqIuipdEXYEAa0XsoFnxv1tRoQERDHxNqthIA7zJXg5WLUj/q5MDJBeMmHuAAzLVmBoaNfYrMCfxeY78ACD7n+q+4y3iAZv9o3yOeYpbXPEYsJX7ZdB44ZQ7ciEj77eYa4KEHza4asBtwifYY1nefhmyGKh8LOncGjpHgKwjuMQ2E3AsOjwJnbFX9uJnoWA58OiPZy2551jcS/LpevTB4xSyhTweewabsM5xVokS0/pDKByaqviFU2eQQvg4MWV2BWHHN24Cm8NCr49k7ThKcmGJqc+hsrUbfpLgZSff2RRz158AGO2A=
    # FIREBASE_SECRET
    - secure: f6cbXr1i7NaIeNFGaa4Z3BygEnaNhIIpoXp9mvvGXd/PcQMXCVddjPByhJjoJPkka4r1zr/tzDEZjJh/BPECEt3b88pDxEX+nr/n3LeR5kSfbGWjvmsDsOD/5JOROTyjmXbxmtpVfl8iZ+EmR/Y+1U6BweyHAztpEhzDsX6wBHHpFaF/jv2LudWbLWidOqfnD4Z3dzlJWpiWGAGZIZyh0SHwgVNHtMy/nMsa16EmZKPQpltwawFvT5ACVxOAYkM/0820kCSlmMTIzfX48OJjDuyMmM2Ra2TFsOgkgsjHSSQJuKDht6DZgdfXfo1kYMCOX963PRIBOzcR0JLOyvpWuOMT1mVg8HPSFVi7ehqCCatpBqowkewJl536ns4OkykANLxZOP5s/fS7Ikq44vQdwbM1eGdmWsx8IlHIxuNALZO2OIdR/XtfcevYk6jpLgoavTZkk5rV+Wk6iX6oK46uUWIm3qnou2Q+fcvmfMtl+2ykfXrSKYc/Nu9OgLnrPLw+DnK1iT/MSk3xxAXS7S4gKF1GbyzefusduhU5U6mGnkXOF4kk5Sm+GLepLMLTbEdumeG7Irmku4IF65I7JM6C8J3Mc8FcnfAJ2YcETz54CUPIhWPmS7KoN+aD8eVV6llMsCiUTHCpk03/149PeTCtszWIBa9jV5rjjwp9GNMxfcI=
